### ISSUE TITLE
Bug with query builder

### ISSUE THREAD

**Issue by scole02** [scole02/CSC482_AIY_voice#1]
asked what time IME 200 was at and exited with an error.

console output before error:
`INFO:root:You said: "when is ime 200"
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.1.9:5000
DEBUG:urllib3.connectionpool:http://192.168.1.9:5000 "GET /query?query=when+is+ime+200 HTTP/1.1" 500 None`

Snippet of stack trace:
 ` File "/home/sam/CSC482/final/query_builder.py", line 201, in generate_sched_response
    res = some_matches(course, df)
  File "/home/sam/CSC482/final/query_builder.py", line 184, in some_matches
    return specific_course_info(course, df)
  File "/home/sam/CSC482/final/query_builder.py", line 153, in specific_course_info
    res += " on " + get_days(row["Days"])
TypeError: can only concatenate str (not "NoneType") to str`

**Comment by EmilyGavrilenko** [comment]
Resolved
